### ISSUE TITLE
Error on Run

### ISSUE THREAD

**Issue by kornface13** [iotaledger/cli-app#13]
I'm getting this error when trying to run this:

```tkorn@iota:~/iri/target$ iota-cli
/usr/local/lib/node_modules/iota-cli-app/lib/config.js:83
  get,
     ^

SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/iota-cli-app/index.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)```

**Comment by jes** [comment]
I fixed it for me by changing the 

```
get,
set
```

to:

```
get: get,
set: set
```

and then adding:

```"use strict";````

to the top of /usr/local/lib/node_modules/iota-cli-app/lib/utils.js
