### ISSUE TITLE
"address" command causes "Invalid transaction hash" every time

### ISSUE THREAD

**Issue by goligo** [iotaledger/cli-app#14]
Whenever I enter "address" into iota-cli, I get 

iota (http://localhost:14265 ✓) 13Mι : address
One minute while we generate the address.
The address is 99WJLKDMXJULBKIJNGVBKKYPSFYLKMQGUFTYWGKBEZIUCYEXIYNDLJSUKS9QOFIM9GRNTNMG9RBANNZBGG99LAWIZH
Now we will register that address into the iota tangle.  One moment.
Error: Request Error: Invalid transaction hash

IRI log file shows

08/09 01:59:49.364 [XNIO-1 task-57] ERROR com.iota.iri.service.API - API Exception: 
java.lang.RuntimeException: Invalid transaction hash
	at com.iota.iri.TransactionValidator.runValidation(TransactionValidator.java:90) ~[iri-1.3.0.jar:na]
	at com.iota.iri.TransactionValidator.validate(TransactionValidator.java:96) ~[iri-1.3.0.jar:na]
	at com.iota.iri.service.API.attachToTangleStatement(API.java:762) [iri-1.3.0.jar:na]
	at com.iota.iri.service.API.process(API.java:219) [iri-1.3.0.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:156) [iri-1.3.0.jar:na]
	at com.iota.iri.service.API.access$000(API.java:80) [iri-1.3.0.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:144) [iri-1.3.0.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.3.0.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.3.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by alesrebec** [comment]
It appears the issue is still present or happened again in iota.lib.js ~0.4.6 that is currently installed.

```
iota (http://localhost:14265 ✓) 100ι : address
One minute while we generate the address.
The address is XXXXXXXXXXXXXXXXXXXX
Now we will register that address into the iota tangle.  One moment.
Error: Request Error: Invalid transaction hash
```

In IRI log I can see this:

```
May 04 15:46:47 CX31E iri[1519]: 05/04 15:46:47.667 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:47 CX31E iri[1519]: 05/04 15:46:47.668 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 6
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.874 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.875 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 24
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.885 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.887 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 14
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.899 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.901 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 13
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.911 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.912 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 24
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.098 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: belowMaxDepth
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.098 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 1
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.102 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.102 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 12
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.118 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: transactionViewModel==extraTip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.118 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 43
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.271 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.271 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 12
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.348 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.349 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 2
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.384 [XNIO-1 task-13] ERROR com.iota.iri.service.API - API Exception:
May 04 15:46:49 CX31E iri[1519]: java.lang.RuntimeException: Invalid transaction hash
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.TransactionValidator.runValidation(TransactionValidator.java:99) ~[iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.TransactionValidator.validate(TransactionValidator.java:109) ~[iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.attachToTangleStatement(API.java:992) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.process(API.java:244) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.processRequest(API.java:184) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.access$000(API.java:57) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API$1.handleRequest(API.java:142) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
May 04 15:46:49 CX31E iri[1519]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
May 04 15:46:49 CX31E iri[1519]:         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
May 04 15:46:51 CX31E iri[1519]: 05/04 15:46:51.471 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2 , toReply = 0 / totalTransactions = 2426380
```
