### ISSUE TITLE
Error: Request Error: Invalid transaction hash on address generate and transfer

### ISSUE THREAD

**Issue by alesrebec** [iotaledger/cli-app#41]
It appears the issue is still present or happened again in iota.lib.js ~0.4.6 that is currently installed.

```
iota (http://localhost:14265 ✓) 100ι : address
One minute while we generate the address.
The address is XXXXXXXXXXXXXXXXXXXX
Now we will register that address into the iota tangle.  One moment.
Error: Request Error: Invalid transaction hash
```

nodeinfo

```
nodeinfo
appName:                            IRI
appVersion:                         1.4.2.4
jreAvailableProcessors:             2
jreFreeMemory:                      498873440
jreVersion:                         1.8.0_162
jreMaxMemory:                       5176295424
jreTotalMemory:                     1635254272
latestMilestone:                    EEEEIFMPUBAZSMF9NXWVRPLXYWQLQFDKSXPOCSXDMAOINHPDY9ZPPQTAROCWBBIYGOLD9FVNVPVG99999
latestMilestoneIndex:               438518
latestSolidSubtangleMilestone:      EEEEIFMPUBAZSMF9NXWVRPLXYWQLQFDKSXPOCSXDMAOINHPDY9ZPPQTAROCWBBIYGOLD9FVNVPVG99999
latestSolidSubtangleMilestoneIndex: 438518
neighbors:                          7
packetsQueueSize:                   0
time:                               1525442069156
tips:                               5061
transactionsToRequest:              0

```

In IRI log I can see this:

```
May 04 15:46:47 CX31E iri[1519]: 05/04 15:46:47.667 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:47 CX31E iri[1519]: 05/04 15:46:47.668 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 6
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.874 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.875 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 24
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.885 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.887 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 14
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.899 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.901 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 13
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.911 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:48 CX31E iri[1519]: 05/04 15:46:48.912 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 24
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.098 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: belowMaxDepth
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.098 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 1
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.102 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.102 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 12
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.118 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: transactionViewModel==extraTip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.118 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 43
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.271 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.271 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 12
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.348 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Reason to stop: TransactionViewModel is a tip
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.349 [XNIO-1 task-10] INFO  com.iota.iri.service.TipsManager - Tx traversed to find tip: 2
May 04 15:46:49 CX31E iri[1519]: 05/04 15:46:49.384 [XNIO-1 task-13] ERROR com.iota.iri.service.API - API Exception:
May 04 15:46:49 CX31E iri[1519]: java.lang.RuntimeException: Invalid transaction hash
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.TransactionValidator.runValidation(TransactionValidator.java:99) ~[iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.TransactionValidator.validate(TransactionValidator.java:109) ~[iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.attachToTangleStatement(API.java:992) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.process(API.java:244) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.processRequest(API.java:184) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API.access$000(API.java:57) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at com.iota.iri.service.API$1.handleRequest(API.java:142) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.4.2.4.jar:na]
May 04 15:46:49 CX31E iri[1519]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
May 04 15:46:49 CX31E iri[1519]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
May 04 15:46:49 CX31E iri[1519]:         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
May 04 15:46:51 CX31E iri[1519]: 05/04 15:46:51.471 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2 , toReply = 0 / totalTransactions = 2426380
```

Looks like the same issue as #14 that was solved in #17 but still present.

**Comment by alesrebec** [comment]
It might help anyone having the same issue.

Run this command in iota-cli.
I'm using it on my own node so it probably wasn't set up with the right number.

`minWeightMagnitude 14`
