### ISSUE TITLE
healthcheck error

### ISSUE THREAD

**Issue by mettenian** [iotaledger/cli-app#5]
iota (http://localhost:14265 ✓): healthcheck
Free memory: ✓
Node sync: ✓
Number of neighbors (4-9): ✓
C:\Users\admin\Documents\GitHub\cli-app\lib\commands\health.js:38
        neighborData.neighbors.filter(
                              ^

TypeError: Cannot read property 'filter' of undefined
    at iotajs.api.getNeighbors (C:\Users\admin\Documents\GitHub\cli-app\lib\commands\health.js:38:31)
    at C:\Users\admin\Documents\GitHub\cli-app\node_modules\iota.lib.js\lib\api\api.js:353:20
    at C:\Users\admin\Documents\GitHub\cli-app\node_modules\iota.lib.js\lib\api\api.js:36:20
    at makeRequest.prepareResult (C:\Users\admin\Documents\GitHub\cli-app\node_modules\iota.lib.js\lib\utils\makeRequest.js:130:12)
    at exports.XMLHttpRequest.request.onreadystatechange (C:\Users\admin\Documents\GitHub\cli-app\node_modules\iota.lib.js\lib\utils\makeRequest.js:61:25)
    at exports.XMLHttpRequest.dispatchEvent (C:\Users\admin\Documents\GitHub\cli-app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (C:\Users\admin\Documents\GitHub\cli-app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (C:\Users\admin\Documents\GitHub\cli-app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mark-bradshaw** [comment]
Thank you for the notification.  I'll follow up soon.

**Comment by mark-bradshaw** [comment]
This has been corrected in master branch now.
